version: 2

project_name: airos-exporter

builds:
  - id: binary
    binary: airos-exporter
    dir: .
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s
      - -w
      - -X github.com/prometheus/common/version.Version={{.Version}}
      - -X github.com/prometheus/common/version.Revision={{.FullCommit}}
      - -X github.com/prometheus/common/version.Branch={{.Branch}}
      - -X github.com/prometheus/common/version.BuildUser={{.Env.USER}}
      - -X github.com/prometheus/common/version.BuildDate={{.Date}}
    goos:
      - linux
    goarch:
      - amd64

archives:
  - id: archives
    builds:
      - binary
    format: "tar.gz"
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    wrap_in_directory: true

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: hotenet
    name: airos-exporter
  prerelease: auto
  name_template: '{{.Tag}}'
